[config]
skip_core_tasks = true

[tasks.default]
alias = "dev"

[tasks.dev]
dependencies = [
    "format",
    "check",
    "test"
]

[tasks.format]
script = ["cargo fmt --all"]

[tasks.check]
script = [
    "cargo check --all-features",
    "cargo clippy --all-features -D warnings",
]
dependencies = [
    "format"
]

[tasks.test]
script = ["cargo test --all-features"]
